export enum SettingsSelectors {
  GeneralButton = 'Settings/GeneralButton',
  LanguageButton = 'Settings/LanguageButton',
  SynchronizationButton = 'Settings/SynchronizationButton',
  AddressBookButton = 'Settings/AddressBookButton',
  RevealViewKeyButton = 'Settings/RevealViewKeyButton',
  RevealPrivateKeyButton = 'Settings/RevealPrivateKeyButton',
  RevealHotKeyButton = 'Settings/RevealHotKeyButton',
  KeysButton = 'Settings/KeysButton',
  SpendingLimitsButton = 'Settings/SpendingLimitsButton',
  GuardianSettingsButton = 'Settings/GuardianSettingsButton',
  RevealSeedPhraseButton = 'Settings/RevealSeedPhraseButton',
  RecoveryPhraseButton = 'Settings/RecoveryPhraseButton',
  DAppsButton = 'Settings/DAppsButton',
  NetworksButton = 'Settings/NetworksButton',
  ActivateAccountButton = 'Settings/ActivateAccountButton',
  RemoveAccountButton = 'Settings/RemoveAccountButton',
  AboutButton = 'Settings/AboutButton',
  FileSettingsButton = 'Settings/FileSettingsButton',
  AdvancedSettingsButton = 'Settings/AdvancedSettingsButton',
  EditMidenFaucetButton = 'Settings/EditMidenFaucetButton',
  EncryptedWalletFile = 'Settings/EncryptedWalletFile',
  SendFeedbackButton = 'Settings/SendFeedbackButton',
  SupportButton = 'Settings/SupportButton'
}
