jest.mock('webextension-polyfill');
jest.mock('@demox-labs/miden-wallet-adapter-base');
jest.mock('@miden-sdk/react');
jest.mock('nanoid');
jest.mock('app/hooks/useGasToken');
jest.mock('app/hooks/useMidenFaucetId');
jest.mock('lib/miden/sdk/miden-client-interface');
jest.mock('lib/miden/sdk/miden-client');
jest.mock('lib/i18n/numbers');
jest.mock('utils/string');
jest.mock('lib/miden/back/vault');
jest.mock('lib/miden/back/dapp');
jest.mock('../src/lib/miden/back/dapp', () => jest.requireActual('../__mocks__/lib/miden/back/dapp'));
