import { MidenNameScriptMismatchError } from './errors';
import {
  REGISTER_DOMAIN_SCRIPT_B64,
  REGISTER_DOMAIN_SCRIPT_BYTE_LENGTH,
  REGISTER_DOMAIN_SCRIPT_ROOT_HEX
} from './register-domain-script';
import { loadRegisterDomainScript } from './script';
import { NoteScript } from './test-support/fake-sdk';

jest.mock('@miden-sdk/miden-sdk/lazy', () => jest.requireActual('lib/miden/name/test-support/fake-sdk'));

function fakeScript(rootHex: string) {
  return { root: () => ({ toHex: () => rootHex }), free: jest.fn() };
}

describe('loadRegisterDomainScript', () => {
  beforeEach(() => {
    NoteScript.deserialize.mockReset();
  });

  it('keeps the generated bytes at the expected length', () => {
    expect(atob(REGISTER_DOMAIN_SCRIPT_B64).length).toBe(REGISTER_DOMAIN_SCRIPT_BYTE_LENGTH);
    expect(REGISTER_DOMAIN_SCRIPT_BYTE_LENGTH).toBe(16_810);
  });

  it('deserializes the bundled bytes and returns the script when the root matches', () => {
    const script = fakeScript(REGISTER_DOMAIN_SCRIPT_ROOT_HEX.toUpperCase().replace('0X', '0x'));
    NoteScript.deserialize.mockReturnValue(script);

    expect(loadRegisterDomainScript()).toBe(script);

    const bytes = NoteScript.deserialize.mock.calls[0]?.[0];
    expect(bytes).toBeInstanceOf(Uint8Array);
    expect(bytes?.length).toBe(16_810);
    // "MAST" magic of a serialized MAST forest.
    expect(Array.from(bytes?.slice(0, 4) ?? [])).toEqual([0x4d, 0x41, 0x53, 0x54]);
    expect(script.free).not.toHaveBeenCalled();
  });

  it('throws and frees the script when the root does not match', () => {
    const script = fakeScript('0x' + '00'.repeat(32));
    NoteScript.deserialize.mockReturnValue(script);

    expect(() => loadRegisterDomainScript()).toThrow(MidenNameScriptMismatchError);
    expect(script.free).toHaveBeenCalledTimes(1);
  });
});
