import { EarnPosition, EarnSummary, EarnVault } from './types';

export const EARN_DATA: {
  summary: EarnSummary;
  positions: EarnPosition[];
  vaults: EarnVault[];
} = {
  summary: {
    totalRewards: '$218.32',
    blendedApy: '~5.2%',
    totalDeposited: '$4, 218.32',
    estimatedRewards: '+$24.50'
  },
  positions: [
    {
      id: 'aave-usdc-1',
      vaultId: 'aave-usdc-ethereum-1',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      amount: '$1,024.50',
      depositedAmount: '$1,000.00',
      rewards: '+$24.50',
      age: '42d',
      activeDuration: '42 days active',
      apy: '5.24%',
      dailyAverage: '+$0.58',
      started: 'Mar 18',
      yearlyEstimate: '+$53.68 / yr',
      withdrawTime: '~30 sec · no lockup',
      route: 'Miden -> Aave (Ethereum)',
      chartData: [
        { label: 'Mar 18', value: 1000 },
        { label: 'Mar 24', value: 1003 },
        { label: 'Mar 30', value: 1008 },
        { label: 'Apr 05', value: 1010 },
        { label: 'Apr 11', value: 1009 },
        { label: 'Apr 17', value: 1012 },
        { label: 'Apr 23', value: 1017 },
        { label: 'Apr 29', value: 1019 },
        { label: 'May 05', value: 1018 },
        { label: 'May 11', value: 1020 },
        { label: 'May 17', value: 1026 },
        { label: 'May 23', value: 1029 },
        { label: 'May 29', value: 1028 },
        { label: 'Jun 04', value: 1029 },
        { label: 'Jun 10', value: 1034 },
        { label: 'Jun 16', value: 1039 },
        { label: 'Jun 22', value: 1041 },
        { label: 'Jun 28', value: 1040 }
      ]
    },
    {
      id: 'aave-usdc-2',
      vaultId: 'aave-usdc-ethereum-1',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      amount: '$1,024.50',
      depositedAmount: '$1,000.00',
      rewards: '+$24.50',
      age: '42d',
      activeDuration: '42 days active',
      apy: '5.24%',
      dailyAverage: '+$0.58',
      started: 'Mar 18',
      yearlyEstimate: '+$53.68 / yr',
      withdrawTime: '~30 sec · no lockup',
      route: 'Miden -> Aave (Ethereum)',
      chartData: [
        { label: 'Mar 18', value: 1000 },
        { label: 'Mar 24', value: 1004 },
        { label: 'Mar 30', value: 1007 },
        { label: 'Apr 05', value: 1011 },
        { label: 'Apr 11', value: 1010 },
        { label: 'Apr 17', value: 1013 },
        { label: 'Apr 23', value: 1016 },
        { label: 'Apr 29', value: 1018 },
        { label: 'May 05', value: 1019 },
        { label: 'May 11', value: 1021 },
        { label: 'May 17', value: 1025 },
        { label: 'May 23', value: 1028 },
        { label: 'May 29', value: 1029 },
        { label: 'Jun 04', value: 1030 },
        { label: 'Jun 10', value: 1033 },
        { label: 'Jun 16', value: 1037 },
        { label: 'Jun 22', value: 1040 },
        { label: 'Jun 28', value: 1041 }
      ]
    }
  ],
  vaults: [
    {
      id: 'aave-usdc-ethereum-1',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      apy: '5.24%',
      apyChange24h: '+0.12% (24h)',
      tvl: '$1.2B',
      risk: 'Low',
      audited: true,
      about: 'Aave is a decentralized lending protocol with battle-tested smart contracts and over $12B TVL.',
      chartData: [
        { label: 'Mar 18', value: 4.88 },
        { label: 'Mar 24', value: 4.92 },
        { label: 'Mar 30', value: 5.01 },
        { label: 'Apr 05', value: 5.08 },
        { label: 'Apr 11', value: 5.1 },
        { label: 'Apr 17', value: 5.09 },
        { label: 'Apr 23', value: 5.09 },
        { label: 'Apr 29', value: 5.14 },
        { label: 'May 05', value: 5.22 },
        { label: 'May 11', value: 5.25 },
        { label: 'May 17', value: 5.24 },
        { label: 'May 23', value: 5.23 },
        { label: 'May 29', value: 5.25 },
        { label: 'Jun 04', value: 5.32 },
        { label: 'Jun 10', value: 5.39 },
        { label: 'Jun 16', value: 5.44 },
        { label: 'Jun 22', value: 5.45 },
        { label: 'Jun 28', value: 5.44 }
      ]
    },
    {
      id: 'aave-usdc-ethereum-2',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      apy: '5.24%',
      apyChange24h: '+0.12% (24h)',
      tvl: '$1.2B',
      risk: 'Low',
      audited: true,
      about: 'Aave is a decentralized lending protocol with battle-tested smart contracts and over $12B TVL.',
      chartData: [
        { label: 'Mar 18', value: 4.9 },
        { label: 'Mar 24', value: 4.95 },
        { label: 'Mar 30', value: 5.0 },
        { label: 'Apr 05', value: 5.08 },
        { label: 'Apr 11', value: 5.13 },
        { label: 'Apr 17', value: 5.12 },
        { label: 'Apr 23', value: 5.14 },
        { label: 'Apr 29', value: 5.18 },
        { label: 'May 05', value: 5.23 },
        { label: 'May 11', value: 5.22 },
        { label: 'May 17', value: 5.24 },
        { label: 'May 23', value: 5.26 },
        { label: 'May 29', value: 5.29 },
        { label: 'Jun 04', value: 5.35 },
        { label: 'Jun 10', value: 5.4 },
        { label: 'Jun 16', value: 5.42 },
        { label: 'Jun 22', value: 5.43 },
        { label: 'Jun 28', value: 5.44 }
      ]
    },
    {
      id: 'aave-usdc-ethereum-3',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      apy: '5.24%',
      apyChange24h: '+0.12% (24h)',
      tvl: '$1.2B',
      risk: 'Low',
      audited: true,
      about: 'Aave is a decentralized lending protocol with battle-tested smart contracts and over $12B TVL.',
      chartData: [
        { label: 'Mar 18', value: 4.86 },
        { label: 'Mar 24', value: 4.91 },
        { label: 'Mar 30', value: 4.98 },
        { label: 'Apr 05', value: 5.05 },
        { label: 'Apr 11', value: 5.12 },
        { label: 'Apr 17', value: 5.11 },
        { label: 'Apr 23', value: 5.16 },
        { label: 'Apr 29', value: 5.17 },
        { label: 'May 05', value: 5.2 },
        { label: 'May 11', value: 5.24 },
        { label: 'May 17', value: 5.25 },
        { label: 'May 23', value: 5.27 },
        { label: 'May 29', value: 5.31 },
        { label: 'Jun 04', value: 5.36 },
        { label: 'Jun 10', value: 5.39 },
        { label: 'Jun 16', value: 5.42 },
        { label: 'Jun 22', value: 5.44 },
        { label: 'Jun 28', value: 5.45 }
      ]
    },
    {
      id: 'aave-usdc-ethereum-4',
      protocol: 'Aave',
      asset: 'USDC',
      network: 'Ethereum',
      apy: '5.24%',
      apyChange24h: '+0.12% (24h)',
      tvl: '$1.2B',
      risk: 'Low',
      audited: true,
      about: 'Aave is a decentralized lending protocol with battle-tested smart contracts and over $12B TVL.',
      chartData: [
        { label: 'Mar 18', value: 4.89 },
        { label: 'Mar 24', value: 4.93 },
        { label: 'Mar 30', value: 5.02 },
        { label: 'Apr 05', value: 5.06 },
        { label: 'Apr 11', value: 5.08 },
        { label: 'Apr 17', value: 5.09 },
        { label: 'Apr 23', value: 5.15 },
        { label: 'Apr 29', value: 5.21 },
        { label: 'May 05', value: 5.24 },
        { label: 'May 11', value: 5.22 },
        { label: 'May 17', value: 5.24 },
        { label: 'May 23', value: 5.27 },
        { label: 'May 29', value: 5.32 },
        { label: 'Jun 04', value: 5.37 },
        { label: 'Jun 10', value: 5.41 },
        { label: 'Jun 16', value: 5.43 },
        { label: 'Jun 22', value: 5.44 },
        { label: 'Jun 28', value: 5.44 }
      ]
    }
  ]
};
