/**
 * Desktop dApp Browser - TypeScript bindings for Tauri commands
 *
 * This module provides functions to control the dApp browser window
 * from the main wallet window.
 */

import { invoke } from '@tauri-apps/api/core';
import { listen, UnlistenFn } from '@tauri-apps/api/event';

// Log to Rust stdout for debugging (kept for future use)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function jsLog(message: string): void {
  invoke('js_log', { message }).catch(() => {});
}

/**
 * Open a dApp in a new browser window
 *
 * @param url - The URL to open
 * @returns Promise that resolves when the window is opened
 */
export async function openDappWindow(url: string): Promise<void> {
  await invoke('open_dapp_window', { url });
}

/**
 * Close the dApp browser window
 *
 * @returns Promise that resolves when the window is closed
 */
export async function closeDappWindow(): Promise<void> {
  await invoke('close_dapp_window');
}

/**
 * Navigate the dApp browser
 *
 * @param action - 'back', 'forward', or 'refresh'
 * @returns Promise that resolves when navigation is triggered
 */
export async function dappNavigate(action: 'back' | 'forward' | 'refresh'): Promise<void> {
  await invoke('dapp_navigate', { action });
}

/**
 * Get the current URL of the dApp browser
 *
 * @returns Promise that resolves with the current URL
 */
export async function dappGetUrl(): Promise<string> {
  return await invoke('dapp_get_url');
}

/**
 * Send a wallet response back to the dApp window
 *
 * @param response - The response to send (will be JSON stringified)
 */
export async function sendDappWalletResponse(response: unknown): Promise<void> {
  await invoke('dapp_wallet_response', { response: JSON.stringify(response) });
}

/**
 * Interface for wallet request event payload
 */
export interface DappWalletRequestEvent {
  request: string; // JSON stringified request
  origin: string;
}

/**
 * Interface for parsed wallet request
 */
export interface DappWalletRequest {
  type: string;
  payload?: unknown;
  reqId: string;
}

/**
 * Listen for wallet requests from the dApp window
 *
 * @param callback - Function to call when a request is received
 * @returns Promise that resolves with an unsubscribe function
 */
export function onDappWalletRequest(
  callback: (request: DappWalletRequest, origin: string) => void | Promise<void>
): Promise<UnlistenFn> {
  return listen<DappWalletRequestEvent>('dapp-wallet-request', event => {
    try {
      const parsed = JSON.parse(event.payload.request) as DappWalletRequest;
      const result = callback(parsed, event.payload.origin);
      // If callback returns a promise, handle errors silently
      if (result && typeof (result as Promise<void>).catch === 'function') {
        (result as Promise<void>).catch(() => {});
      }
    } catch {
      // Silent fail for parse errors
    }
  });
}

/**
 * Listen for dApp window close events
 *
 * @param callback - Function to call when the window is closed
 * @returns Promise that resolves with an unsubscribe function
 */
export function onDappWindowClose(callback: () => void): Promise<UnlistenFn> {
  return listen('dapp-window-closed', () => {
    callback();
  });
}

/**
 * Interface for confirmation response
 */
export interface DappConfirmationResponse {
  requestId: string;
  confirmed: boolean;
}

/**
 * Listen for confirmation responses from the dApp overlay
 *
 * @param callback - Function to call when a response is received
 * @returns Promise that resolves with an unsubscribe function
 */
export function onDappConfirmationResponse(
  callback: (response: DappConfirmationResponse) => void
): Promise<UnlistenFn> {
  return listen<string>('dapp-confirmation-response', event => {
    try {
      const response = JSON.parse(event.payload) as DappConfirmationResponse;
      callback(response);
    } catch {
      // Silent fail for parse errors
    }
  });
}

/**
 * Show a confirmation overlay in the dApp browser window
 *
 * @param overlayScript - The JavaScript to inject (generated by generateDesktopConfirmationOverlay)
 */
export async function showDappConfirmationOverlay(overlayScript: string): Promise<void> {
  await invoke('show_dapp_confirmation_overlay', { overlayScript });
}

/**
 * Generate the desktop confirmation overlay script
 */
export function generateDesktopConfirmationOverlay(
  requestId: string,
  appName: string,
  origin: string,
  network: string,
  shortAccountId: string,
  isTransaction: boolean,
  transactionMessages: string[],
  translations: {
    connectionRequest: string;
    transactionRequest: string;
    account: string;
    network: string;
    noAccountSelected: string;
    deny: string;
    approve: string;
    confirm: string;
  }
): string {
  const escapeHtml = (str: string): string =>
    str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
      .replace(/`/g, '&#96;');

  const escapedAppName = escapeHtml(appName);
  const escapedOrigin = escapeHtml(origin);
  const escapedNetwork = escapeHtml(network);
  const escapedAccountId = escapeHtml(shortAccountId || translations.noAccountSelected);

  return `
(function() {
  // Remove any existing overlay
  var existing = document.getElementById('miden-confirmation-overlay');
  if (existing) existing.remove();

  // Create overlay container
  var overlay = document.createElement('div');
  overlay.id = 'miden-confirmation-overlay';
  overlay.innerHTML = \`
    <style>
      #miden-confirmation-overlay {
        position: fixed;
        inset: 0;
        z-index: 999999;
        display: flex;
        align-items: center;
        justify-content: center;
        background: rgba(255, 255, 255, 0.1);
        backdrop-filter: blur(20px) saturate(1.5);
        -webkit-backdrop-filter: blur(20px) saturate(1.5);
        padding: 16px;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      }
      #miden-confirmation-modal {
        background: white;
        border-radius: 16px;
        width: 100%;
        max-width: 400px;
        box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
        overflow: hidden;
      }
      .miden-modal-header {
        padding: 24px;
        border-bottom: 1px solid #f0f0f0;
        display: flex;
        align-items: center;
        gap: 16px;
      }
      .miden-modal-icon {
        width: 48px;
        height: 48px;
        border-radius: 12px;
        background: #EEF2FF;
        display: flex;
        align-items: center;
        justify-content: center;
        shrink: 0;
      }
      .miden-modal-icon svg {
        width: 24px;
        height: 24px;
        color: #6366F1;
      }
      .miden-modal-title-container {
        flex: 1;
        min-width: 0;
      }
      .miden-modal-title {
        font-size: 18px;
        font-weight: 600;
        color: #1f2937;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        margin: 0 0 4px 0;
      }
      .miden-modal-subtitle {
        font-size: 14px;
        color: #6b7280;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        margin: 0;
      }
      .miden-modal-content {
        padding: 24px;
      }
      .miden-modal-description {
        color: #4b5563;
        margin-bottom: 16px;
        font-size: 15px;
      }
      .miden-info-box {
        background: #f9fafb;
        border-radius: 12px;
        padding: 16px;
        margin-bottom: 16px;
      }
      .miden-info-label {
        font-size: 12px;
        color: #6b7280;
        margin-bottom: 4px;
      }
      .miden-info-value {
        font-size: 14px;
        color: #1f2937;
        font-family: ui-monospace, monospace;
      }
      .miden-info-value.capitalize {
        text-transform: capitalize;
        font-family: inherit;
      }
      .miden-tx-messages {
        background: #f9fafb;
        border-radius: 12px;
        padding: 16px;
        margin-bottom: 16px;
      }
      .miden-tx-message {
        font-size: 13px;
        color: #4b5563;
        padding: 8px 0;
        border-bottom: 1px solid #e5e7eb;
      }
      .miden-tx-message:last-child {
        border-bottom: none;
      }
      .miden-modal-actions {
        padding: 24px;
        border-top: 1px solid #f0f0f0;
        display: flex;
        gap: 12px;
      }
      .miden-btn {
        flex: 1;
        padding: 14px 24px;
        border-radius: 24px;
        font-size: 15px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s;
        border: none;
      }
      .miden-btn-deny {
        background: white;
        border: 2px solid #f97316;
        color: #f97316;
      }
      .miden-btn-deny:hover {
        background: #fff7ed;
      }
      .miden-btn-approve {
        background: #6366F1;
        color: white;
      }
      .miden-btn-approve:hover {
        background: #4f46e5;
      }
      .miden-btn-approve:disabled {
        background: #c7d2fe;
        cursor: not-allowed;
      }
    </style>
    <div id="miden-confirmation-modal">
      <div class="miden-modal-header">
        <div class="miden-modal-icon">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
          </svg>
        </div>
        <div class="miden-modal-title-container">
          <h2 class="miden-modal-title">${escapedAppName}</h2>
          <p class="miden-modal-subtitle">${escapedOrigin}</p>
        </div>
      </div>
      <div class="miden-modal-content">
        <p class="miden-modal-description">${isTransaction ? escapeHtml(translations.transactionRequest) : escapeHtml(translations.connectionRequest)}</p>
        ${
          isTransaction
            ? `<div class="miden-tx-messages">
                ${transactionMessages.map(msg => `<div class="miden-tx-message">${escapeHtml(msg)}</div>`).join('')}
              </div>`
            : `<div class="miden-info-box">
                <p class="miden-info-label">${escapeHtml(translations.account)}</p>
                <p class="miden-info-value">${escapedAccountId}</p>
              </div>`
        }
        <div class="miden-info-box" style="margin-bottom: 0;">
          <p class="miden-info-label">${escapeHtml(translations.network)}</p>
          <p class="miden-info-value capitalize">${escapedNetwork}</p>
        </div>
      </div>
      <div class="miden-modal-actions">
        <button class="miden-btn miden-btn-deny" id="miden-btn-deny">${escapeHtml(translations.deny)}</button>
        <button class="miden-btn miden-btn-approve" id="miden-btn-approve" ${!shortAccountId && !isTransaction ? 'disabled' : ''}>${isTransaction ? escapeHtml(translations.confirm) : escapeHtml(translations.approve)}</button>
      </div>
    </div>
  \`;

  document.body.appendChild(overlay);

  // Handle button clicks
  document.getElementById('miden-btn-deny').addEventListener('click', function() {
    sendResponse(false);
  });

  document.getElementById('miden-btn-approve').addEventListener('click', function() {
    sendResponse(true);
  });

  function sendResponse(confirmed) {
    // Remove overlay
    overlay.remove();

    // Send response via URL navigation (intercepted by Tauri)
    var response = JSON.stringify({
      requestId: '${requestId}',
      confirmed: confirmed
    });
    var encoded = btoa(unescape(encodeURIComponent(response)));
    var responseUrl = 'https://miden-wallet-confirmation-response/' + encoded;

    // Use iframe to avoid affecting page state
    var iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    iframe.src = responseUrl;
    document.body.appendChild(iframe);
    setTimeout(function() { iframe.remove(); }, 1000);
  }
})();
`;
}
