//! Wallet-window gate for every app-defined Tauri command.
//!
//! Tauri enforces the capability ACL for a command only when it is a `plugin:`
//! command OR the app ships its own ACL manifest (`tauri-2.11.0`
//! `src/webview/mod.rs`: `if (plugin_command.is_some() || has_app_acl_manifest) &&
//! … && invoke.acl.is_none() { reject }`). `has_app_acl_manifest` is
//! `acl.contains_key("__app-acl__")`, which is populated only when
//! `src-tauri/permissions/` defines app permissions. Until it did, every command in
//! the `generate_handler!` list skipped the ACL check for EVERY webview and both
//! `Origin::Local` and `Origin::Remote` — and the dApp-browser window loads
//! arbitrary third-party pages with `withGlobalTauri: true`, so one line of page
//! script (`window.__TAURI__.core.invoke('delete_hardware_key')`) reached them all.
//! `src-tauri/permissions/app.toml` now closes that hole.
//!
//! This module is the second, independent lock: the app commands all belong to the
//! wallet UI, so each one refuses a request that did not come from the `main`
//! webview. It holds even if the permission manifest is ever dropped, renamed, or
//! out-scoped, and unlike the manifest it is unit-testable.

/// Label of the webview that hosts the wallet UI. Every app command is for it.
pub const WALLET_WEBVIEW_LABEL: &str = "main";

/// Refusal returned to a caller outside the wallet webview. Deliberately says
/// nothing about which commands exist.
pub const NOT_WALLET_WEBVIEW: &str = "Command not available to this webview";

/// Whether `label` names the wallet's own webview.
///
/// The dApp-browser window is built with the label `dapp-browser`
/// (`dapp_browser::open_dapp_window`), so a request originating in a page the user
/// merely visited never matches.
pub fn is_wallet_webview(label: &str) -> bool {
    label == WALLET_WEBVIEW_LABEL
}

/// `Ok(())` when the invoking webview is the wallet's, `Err` otherwise.
pub fn ensure_wallet_webview(webview: &tauri::Webview) -> Result<(), String> {
    if is_wallet_webview(webview.label()) {
        return Ok(());
    }
    log::info!(
        "Refusing an app command invoked from webview `{}`",
        webview.label()
    );
    Err(NOT_WALLET_WEBVIEW.to_string())
}

#[cfg(test)]
mod tests {
    use super::{is_wallet_webview, WALLET_WEBVIEW_LABEL};
    use std::fs;
    use std::path::Path;

    #[test]
    fn only_the_wallet_webview_may_invoke_app_commands() {
        assert!(is_wallet_webview(WALLET_WEBVIEW_LABEL));
        // The window that loads arbitrary third-party pages.
        assert!(!is_wallet_webview("dapp-browser"));
        assert!(!is_wallet_webview(""));
        // No prefix/suffix slack: a webview cannot pick a label that merely
        // contains the wallet's.
        assert!(!is_wallet_webview("main-2"));
        assert!(!is_wallet_webview("not-main"));
    }

    #[test]
    fn the_app_defines_its_own_acl_manifest() {
        // Without an `__app-acl__` key Tauri skips the capability check for every
        // app-defined command (see the module docs), so this asserts the generated
        // manifest that `src-tauri/permissions/` produces is actually there.
        let manifests = Path::new(env!("CARGO_MANIFEST_DIR")).join("gen/schemas/acl-manifests.json");
        let raw = fs::read_to_string(&manifests)
            .unwrap_or_else(|e| panic!("{} is generated by tauri-build: {e}", manifests.display()));
        let parsed: serde_json::Value =
            serde_json::from_str(&raw).expect("acl-manifests.json is JSON");
        let manifest = parsed
            .get("__app-acl__")
            .expect("app commands are ACL-checked only when the app ships its own manifest");
        let permissions = manifest
            .get("permissions")
            .and_then(|p| p.as_object())
            .expect("the app manifest carries its permissions");
        assert!(
            permissions.contains_key("allow-wallet-window-commands"),
            "the capability in capabilities/default.json must resolve to a real permission"
        );
    }
}
