name: test

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
    secrets:
      ENV:
        required: false
      SSH_DEPLOY_KEY:
        required: false

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Use Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # - name: Create Dotenv File
      #   run: |
      #     echo "${{ secrets.ENV }}" > .env

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run TypeScript Check
        uses: borales/actions-yarn@v4
        with:
          cmd: ts

      - name: Run Unit Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build chrome
        uses: borales/actions-yarn@v4
        with:
          cmd: build:chrome
        env:
          MIDEN_USE_MOCK_CLIENT: 'true'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright E2E
        run: xvfb-run -a yarn test:e2e
